name: Release
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test
        run: go test -v ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Coding Container Registry
        uses: docker/login-action@v1
        with:
          registry: cross-border-e-commerce-docker.pkg.coding.net
          username: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_PASSWORD }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          platforms: linux/amd64
          tags: |
            cross-border-e-commerce-docker.pkg.coding.net/cross-border-e-commerce/prisma-db/prisma-data-proxy:latest
          push: true